# Generated by Django 2.0.6 on 2018-07-30 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('table_name', models.CharField(max_length=255)),
                ('table_id', models.IntegerField()),
                ('mark_as_read', models.IntegerField()),
                ('from_employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_from_employee', to=settings.AUTH_USER_MODEL)),
                ('to_employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_to_employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
